[build]
builder = "nixpacks"

[build.nixpacksConfig]
build-cmd = "npm ci && npx prisma generate && npm run build"
start-cmd = "node dist/src/main.js"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "4001"
